#!/usr/bin/env python3
"""Generate `docs/reference/index.qmd` — the API reference — with quartodoc.

The reference is generated from the signatures and docstrings themselves, by the
standard Quarto mechanism, so it stays in the same site, theme and search index
as the guide. `quartodoc` reads its configuration from the `quartodoc:` block in
`docs/_quarto.yml`.

What this adds around it:

- **The filename.** quartodoc's single-page builder writes `index.qmd.qmd`.
- **Frontmatter.** The single-page builder emits sections and no title.
- **A coverage check.** Every name in `plugkit.__all__` must appear as an anchor.
  A public name absent from the reference is a name nobody can look up.

Build:
    uv run --with quartodoc --extra dev python scripts/build-reference.py

`quartodoc` is a documentation-time tool. Nothing in `src/plugkit/` imports it,
and `pyproject.toml` still declares `dependencies = []`.
"""
from __future__ import annotations

import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "reference" / "index.qmd"

FRONTMATTER = """---
title: "API reference"
subtitle: "Every public name, with its signature — generated from the source by quartodoc"
toc-depth: 3
---

Generated by `scripts/build-reference.py` from docstrings and signatures. The
guide teaches these; this page is for looking one up. Anything missing a
description here is missing a docstring in the source.

"""


def exports() -> list[str]:
    """`plugkit.__all__`, read without importing the package."""
    source = (ROOT / "src/plugkit/__init__.py").read_text(encoding="utf-8")
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Assign) and any(
            getattr(target, "id", "") == "__all__" for target in node.targets
        ):
            return [element.value for element in node.value.elts]
    raise SystemExit("src/plugkit/__init__.py has no __all__")


def _delink(body: str) -> tuple[str, list[str]]:
    """Turn links to anchors this page does not define into plain code spans.

    A member table links every entry, including attributes, but the single-page
    style emits a section only for the members it documents in full. The link is
    then a click that goes nowhere — worse than no link, and it would go nowhere
    on the published site too, not only in the one-page build.
    """
    anchors = set(re.findall(r"\{ #(plugkit\.[\w.]+) \}", body))
    dangling: list[str] = []

    def fix(match: re.Match) -> str:
        text, target = match.group(1), match.group(2)
        if target in anchors:
            return match.group(0)
        dangling.append(target)
        return f"`{text}`"

    return re.sub(r"\[([^\]]+)\]\(#(plugkit\.[\w.]+)\)", fix, body), sorted(set(dangling))


def main() -> None:
    completed = subprocess.run(
        ["quartodoc", "build"], cwd=DOCS, capture_output=True, text=True
    )
    if completed.returncode != 0:
        raise SystemExit(completed.stderr or completed.stdout)
    # griffe's warnings are the useful half of the output — a parameter with no
    # annotation, a docstring section it could not parse.
    for line in (completed.stderr or "").splitlines():
        print(f"  griffe: {line}")

    written = sorted(OUT.parent.glob("index.qmd*"))
    if not written:
        raise SystemExit("quartodoc wrote no page")
    page = max(written, key=lambda p: p.stat().st_mtime)
    body = page.read_text(encoding="utf-8")
    for stray in written:
        stray.unlink()

    body, dangling = _delink(body)
    for target in dangling:
        print(f"  de-linked {target}: listed in a table, but single-page emits no section")

    OUT.write_text(FRONTMATTER + body.strip() + "\n")

    missing = [name for name in exports() if f"{{ #plugkit.{name} }}" not in body]
    if missing:
        raise SystemExit(
            "public names with no entry in the reference — add them to the "
            "`quartodoc: sections:` block in docs/_quarto.yml:\n  " + "\n  ".join(missing)
        )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(OUT.read_text()):,} bytes, {len(exports())} names)")


if __name__ == "__main__":
    sys.exit(main())
